table Vw_Inventory_Aging_report
	lineageTag: d0f8fce8-9282-4640-b570-e0fffea34927

	measure P1:Quantity = ```
			
			VAR Start_date =MAX(Vw_Inventory_Aging_report[DatePhysical])
			Var End_Date = MAX(Vw_Inventory_Aging_report[DatePhysical])-90
			Var Result =
			    CALCULATE(Sum(Vw_Inventory_Aging_report[Qty])
			    ,
			    Vw_Inventory_Aging_report[DatePhysical]>= End_Date && 
			    Vw_Inventory_Aging_report[DatePhysical]<= Start_date
			    )
			return Result
			```
		lineageTag: 24a01ecc-0afe-43db-ac1e-283f7a06d5df

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure P2:Quantity = ```
			
			VAR Start_date =MAX(Vw_Inventory_Aging_report[DatePhysical])-91
			Var End_Date = MAX(Vw_Inventory_Aging_report[DatePhysical])-180
			Var Result =
			    CALCULATE(Sum(Vw_Inventory_Aging_report[Qty])
			    ,
			    Vw_Inventory_Aging_report[DatePhysical]>= End_Date && 
			    Vw_Inventory_Aging_report[DatePhysical]<= Start_date
			    )
			return Result
			```
		lineageTag: 9e14fc94-4342-42c8-a22d-cb80b5db61f4

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure P3:Quantity = ```
			
			VAR Start_date =MAX(Vw_Inventory_Aging_report[DatePhysical])-181
			Var End_Date = MAX(Vw_Inventory_Aging_report[DatePhysical])-365
			Var Result =
			    CALCULATE(Sum(Vw_Inventory_Aging_report[Qty])
			    ,
			    Vw_Inventory_Aging_report[DatePhysical]>= End_Date && 
			    Vw_Inventory_Aging_report[DatePhysical]<= Start_date
			    )
			return Result
			```
		lineageTag: daad836a-f68e-483a-9263-5bf675acf283

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure P4:Quantity = ```
			
			VAR Start_date =MAX(Vw_Inventory_Aging_report[DatePhysical])-366
			Var End_Date = MAX(Vw_Inventory_Aging_report[DatePhysical])-545
			Var Result =
			    CALCULATE(Sum(Vw_Inventory_Aging_report[Qty])
			    ,
			    Vw_Inventory_Aging_report[DatePhysical]>= End_Date && 
			    Vw_Inventory_Aging_report[DatePhysical]<= Start_date
			    )
			return Result
			```
		lineageTag: 2fa714eb-f47a-4743-a694-040e7290ffdb

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure P5:Quantity = ```
			
			VAR Start_date =MAX(Vw_Inventory_Aging_report[DatePhysical])-546
			Var End_Date = MAX(Vw_Inventory_Aging_report[DatePhysical])-730
			Var Result =
			    CALCULATE(Sum(Vw_Inventory_Aging_report[Qty])
			    ,
			    Vw_Inventory_Aging_report[DatePhysical]>= End_Date && 
			    Vw_Inventory_Aging_report[DatePhysical]<= Start_date
			    )
			return Result
			```
		lineageTag: 32c179c3-3244-41f4-88f0-d193b667567c

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure P1:Amount = ```
			
			VAR Start_date =MAX(Vw_Inventory_Aging_report[DatePhysical])
			Var End_Date = MAX(Vw_Inventory_Aging_report[DatePhysical])-90
			Var Result =
			    CALCULATE(Sum(Vw_Inventory_Aging_report[Amount])
			    ,
			    Vw_Inventory_Aging_report[DatePhysical]>= End_Date && 
			    Vw_Inventory_Aging_report[DatePhysical]<= Start_date
			    )
			return Result
			```
		lineageTag: 715ffd1a-15ba-4214-aa55-d699c9b01749

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure P2:Amount = ```
			
			VAR Start_date =MAX(Vw_Inventory_Aging_report[DatePhysical])-91
			Var End_Date = MAX(Vw_Inventory_Aging_report[DatePhysical])-180
			Var Result =
			    CALCULATE(Sum(Vw_Inventory_Aging_report[Amount])
			    ,
			    Vw_Inventory_Aging_report[DatePhysical]>= End_Date && 
			    Vw_Inventory_Aging_report[DatePhysical]<= Start_date
			    )
			return Result
			```
		lineageTag: 99a8ebb0-742c-4f1b-8065-0b1daf76f235

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure P3:Amount = ```
			
			VAR Start_date =MAX(Vw_Inventory_Aging_report[DatePhysical])-181
			Var End_Date = MAX(Vw_Inventory_Aging_report[DatePhysical])-365
			Var Result =
			    CALCULATE(Sum(Vw_Inventory_Aging_report[Amount])
			    ,
			    Vw_Inventory_Aging_report[DatePhysical]>= End_Date && 
			    Vw_Inventory_Aging_report[DatePhysical]<= Start_date
			    )
			return Result
			```
		lineageTag: c5eb585f-831b-43ea-9d60-ccbee4326d9b

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure P4:Amount = ```
			
			VAR Start_date =MAX(Vw_Inventory_Aging_report[DatePhysical])-366
			Var End_Date = MAX(Vw_Inventory_Aging_report[DatePhysical])-545
			Var Result =
			    CALCULATE(Sum(Vw_Inventory_Aging_report[Amount])
			    ,
			    Vw_Inventory_Aging_report[DatePhysical]>= End_Date && 
			    Vw_Inventory_Aging_report[DatePhysical]<= Start_date
			    )
			return Result
			```
		lineageTag: 0897f54e-8ff5-4168-bac2-e2003aabd7d2

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure P5:Amount =
			
			VAR Start_date =MAX(Vw_Inventory_Aging_report[DatePhysical])-546
			Var End_Date = MAX(Vw_Inventory_Aging_report[DatePhysical])-730
			Var Result =
			    CALCULATE(Sum(Vw_Inventory_Aging_report[Amount])
			    ,
			    Vw_Inventory_Aging_report[DatePhysical]>= End_Date &&
			    Vw_Inventory_Aging_report[DatePhysical]<= Start_date
			    )
			return Result
		lineageTag: 80e75058-7c1b-41fc-b597-73ba2e36bad6

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average Cost' = DIVIDE(sum(Vw_Inventory_Aging_report[Amount]),sum(Vw_Inventory_Aging_report[Qty]))
		lineageTag: 28e16753-daa0-4e2d-b074-9805f0a0535c

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure P6:Quantity =
			
			VAR Start_date =MAX(Vw_Inventory_Aging_report[DatePhysical])-731
			Var End_Date = MAX(Vw_Inventory_Aging_report[DatePhysical])-730
			Var Result =
			    CALCULATE(Sum(Vw_Inventory_Aging_report[Qty])
			    ,
			    /*Vw_Inventory_Aging_report[DatePhysical]>= End_Date &&  */
			    Vw_Inventory_Aging_report[DatePhysical]<= Start_date
			    )
			return Result
		lineageTag: 7b22b2e0-b42f-4fe6-ab40-4a56ccea2aad

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure P6:Amount =
			
			VAR Start_date =MAX(Vw_Inventory_Aging_report[DatePhysical])-731
			Var End_Date = MAX(Vw_Inventory_Aging_report[DatePhysical])-730
			Var Result =
			    CALCULATE(Sum(Vw_Inventory_Aging_report[Amount])
			    ,
			    /*Vw_Inventory_Aging_report[DatePhysical]>= End_Date &&  */
			    Vw_Inventory_Aging_report[DatePhysical]<= Start_date
			    )
			return Result
		lineageTag: 4466cbf8-8790-4386-b3cc-6e99287f1129

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column itemGroupId
		dataType: string
		lineageTag: de0b1d18-a52a-4c2e-ab50-046db2bd8ff0
		summarizeBy: none
		sourceColumn: itemGroupId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Qty
		dataType: double
		lineageTag: a6022a00-86ab-4ca1-a403-ea74d04ca09f
		summarizeBy: sum
		sourceColumn: Qty

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DatePhysical
		dataType: dateTime
		formatString: Short Date
		lineageTag: 0ebb799b-2203-4c45-94af-1e9af38e0cc8
		summarizeBy: none
		sourceColumn: DatePhysical

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Amount
		dataType: double
		lineageTag: 81cfa84d-c854-43d5-825d-411a847773b3
		summarizeBy: sum
		sourceColumn: Amount

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ItemId
		dataType: string
		lineageTag: eb056e31-64e4-45db-a7bb-e00f8aca4fc3
		summarizeBy: none
		sourceColumn: ItemId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UnitId
		dataType: string
		lineageTag: 846bcc2d-7b11-46a8-a624-3ba7c797426d
		summarizeBy: none
		sourceColumn: UnitId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column namealias
		dataType: string
		lineageTag: 9f0d6399-685d-4fcf-9e7c-f08d1d84f424
		summarizeBy: none
		sourceColumn: namealias

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Inventory value Qty.'
		dataType: double
		lineageTag: d2f77b58-23e2-4def-b8cc-e15015dddbec
		summarizeBy: sum
		sourceColumn: Inventory value Qty.

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Inventory value'
		dataType: double
		lineageTag: 9119fd73-1f5e-499b-b484-51f930927bf0
		summarizeBy: sum
		sourceColumn: Inventory value

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CONFIGID
		dataType: string
		lineageTag: bf674b2c-cb6f-4a49-9c5d-c479a717bd0e
		summarizeBy: none
		sourceColumn: CONFIGID

		annotation SummarizationSetBy = Automatic

	column INVENTBATCHID
		dataType: string
		lineageTag: affcefce-b91e-4653-82fd-85525f963c5a
		summarizeBy: none
		sourceColumn: INVENTBATCHID

		annotation SummarizationSetBy = Automatic

	column INVENTCOLORID
		dataType: string
		lineageTag: 4413872d-bf06-471c-a7b6-301b48cf6d73
		summarizeBy: none
		sourceColumn: INVENTCOLORID

		annotation SummarizationSetBy = Automatic

	column INVENTDIMID
		dataType: string
		lineageTag: aa412b87-9f62-44dc-9645-0c6c5f7dc1e3
		summarizeBy: none
		sourceColumn: INVENTDIMID

		annotation SummarizationSetBy = Automatic

	column INVENTGTDID_RU
		dataType: string
		lineageTag: 1585e1e7-e70d-47f0-8cec-55b667847537
		summarizeBy: none
		sourceColumn: INVENTGTDID_RU

		annotation SummarizationSetBy = Automatic

	column INVENTLOCATIONID
		dataType: string
		lineageTag: 04bc5298-1c4c-4e2b-914c-6d714eb709fc
		summarizeBy: none
		sourceColumn: INVENTLOCATIONID

		annotation SummarizationSetBy = Automatic

	column INVENTOWNERID_RU
		dataType: string
		lineageTag: f4edab9b-e557-456f-bada-8ef37b312bad
		summarizeBy: none
		sourceColumn: INVENTOWNERID_RU

		annotation SummarizationSetBy = Automatic

	column INVENTPROFILEID_RU
		dataType: string
		lineageTag: 28469062-4d66-41e3-8cd1-57b6fb03ddcf
		summarizeBy: none
		sourceColumn: INVENTPROFILEID_RU

		annotation SummarizationSetBy = Automatic

	column INVENTSERIALID
		dataType: string
		lineageTag: 1b805d24-7043-4579-ae9a-6369c445cde2
		summarizeBy: none
		sourceColumn: INVENTSERIALID

		annotation SummarizationSetBy = Automatic

	column INVENTSITEID
		dataType: string
		lineageTag: 45ff779e-f0f1-4b3a-ba7d-356f607df908
		summarizeBy: none
		sourceColumn: INVENTSITEID

		annotation SummarizationSetBy = Automatic

	column INVENTSIZEID
		dataType: string
		lineageTag: df8bc49f-315e-41fd-bd0a-26ad99298cd7
		summarizeBy: none
		sourceColumn: INVENTSIZEID

		annotation SummarizationSetBy = Automatic

	column INVENTSTATUSID
		dataType: string
		lineageTag: 5abc99d0-c59f-411e-baa9-640b99d4e7c1
		summarizeBy: none
		sourceColumn: INVENTSTATUSID

		annotation SummarizationSetBy = Automatic

	column INVENTSTYLEID
		dataType: string
		lineageTag: 2b6f3675-05c0-435d-9561-8d75b04cd815
		summarizeBy: none
		sourceColumn: INVENTSTYLEID

		annotation SummarizationSetBy = Automatic

	column LICENSEPLATEID
		dataType: string
		lineageTag: 64c37eca-f2ac-4dc0-b3f1-6b60b1ff13da
		summarizeBy: none
		sourceColumn: LICENSEPLATEID

		annotation SummarizationSetBy = Automatic

	column WMSLOCATIONID
		dataType: string
		lineageTag: 559211ec-ca99-4505-9d6c-62f2eb76eb72
		summarizeBy: none
		sourceColumn: WMSLOCATIONID

		annotation SummarizationSetBy = Automatic

	column WMSPALLETID
		dataType: string
		lineageTag: 277c5f0e-7bce-4d3c-b110-8b7aef50682f
		summarizeBy: none
		sourceColumn: WMSPALLETID

		annotation SummarizationSetBy = Automatic

	column SHA1HASHHEX
		dataType: string
		lineageTag: 8ce469bd-be91-4d31-b8bc-cce03b4124f2
		summarizeBy: none
		sourceColumn: SHA1HASHHEX

		annotation SummarizationSetBy = Automatic

	column MODIFIEDDATETIME
		dataType: dateTime
		formatString: General Date
		lineageTag: de10dbf5-139b-4dcb-a5e4-071deb935af7
		summarizeBy: none
		sourceColumn: MODIFIEDDATETIME

		variation Variation
			isDefault
			relationship: 27133e62-1f3e-4a21-b4b5-155e6cbae93c
			defaultHierarchy: LocalDateTable_affee1d6-8968-4c01-8223-bdd82d4604ef.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column MODIFIEDBY
		dataType: string
		lineageTag: 12829ec6-4777-47be-bb7a-dce4d8d8a0b1
		summarizeBy: none
		sourceColumn: MODIFIEDBY

		annotation SummarizationSetBy = Automatic

	column CREATEDDATETIME
		dataType: dateTime
		formatString: General Date
		lineageTag: 87e8e9e4-a7e9-4a05-8d3a-fdd9909c9224
		summarizeBy: none
		sourceColumn: CREATEDDATETIME

		variation Variation
			isDefault
			relationship: e4b07349-4087-4f7f-9b54-507bd4447e77
			defaultHierarchy: LocalDateTable_a8bca540-d530-4154-aae4-0e94d28b2620.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column DATAAREAID
		dataType: string
		lineageTag: 6daebe21-5d01-4222-9ea9-19c976844536
		summarizeBy: none
		sourceColumn: DATAAREAID

		annotation SummarizationSetBy = Automatic

	column RECVERSION
		dataType: int64
		formatString: 0
		lineageTag: cd396b60-8a6a-4933-b6cd-0bb7778a0116
		summarizeBy: sum
		sourceColumn: RECVERSION

		annotation SummarizationSetBy = Automatic

	column PARTITION
		dataType: int64
		formatString: 0
		lineageTag: c54ed5b9-b80c-4aaa-959b-a609a85f67dd
		summarizeBy: sum
		sourceColumn: PARTITION

		annotation SummarizationSetBy = Automatic

	column RECID
		dataType: int64
		formatString: 0
		lineageTag: e8c31f9b-f77e-4172-8e93-688ea3673556
		summarizeBy: count
		sourceColumn: RECID

		annotation SummarizationSetBy = Automatic

	column INVENTDIMENSION1
		dataType: string
		lineageTag: 672b8145-9590-4e4c-b298-30de35447fbd
		summarizeBy: none
		sourceColumn: INVENTDIMENSION1

		annotation SummarizationSetBy = Automatic

	column INVENTDIMENSION2
		dataType: string
		lineageTag: af5687a8-7ddd-4902-924e-ed2df71ad02f
		summarizeBy: none
		sourceColumn: INVENTDIMENSION2

		annotation SummarizationSetBy = Automatic

	column INVENTDIMENSION3
		dataType: string
		lineageTag: a5035884-af8d-4b31-9259-2c5125aee2f3
		summarizeBy: none
		sourceColumn: INVENTDIMENSION3

		annotation SummarizationSetBy = Automatic

	column INVENTDIMENSION4
		dataType: string
		lineageTag: bb81647a-23e4-4f04-a167-afd3b4b5c710
		summarizeBy: none
		sourceColumn: INVENTDIMENSION4

		annotation SummarizationSetBy = Automatic

	column INVENTDIMENSION5
		dataType: string
		lineageTag: 5f9116d8-d05f-44f5-b849-36c212b913ce
		summarizeBy: none
		sourceColumn: INVENTDIMENSION5

		annotation SummarizationSetBy = Automatic

	column INVENTDIMENSION6
		dataType: string
		lineageTag: 0f1458bb-c44b-46a5-bd54-699e35a6b94c
		summarizeBy: none
		sourceColumn: INVENTDIMENSION6

		annotation SummarizationSetBy = Automatic

	column INVENTDIMENSION7
		dataType: string
		lineageTag: 1c0073e0-a112-4cb2-8a84-340c4bd3df4a
		summarizeBy: none
		sourceColumn: INVENTDIMENSION7

		annotation SummarizationSetBy = Automatic

	column INVENTDIMENSION8
		dataType: string
		lineageTag: 6dc466db-ea84-4073-8e78-183c15a18b70
		summarizeBy: none
		sourceColumn: INVENTDIMENSION8

		annotation SummarizationSetBy = Automatic

	column INVENTDIMENSION9
		dataType: dateTime
		formatString: General Date
		lineageTag: 160f9154-0ab8-46cd-9c69-f9549139d89c
		summarizeBy: none
		sourceColumn: INVENTDIMENSION9

		variation Variation
			isDefault
			relationship: 7b6a4159-f715-4b5c-8fa5-5857cf105084
			defaultHierarchy: LocalDateTable_bdde352d-f122-445e-86d7-5818eb0c3866.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column INVENTDIMENSION9TZID
		dataType: int64
		formatString: 0
		lineageTag: 4c7955c3-9c52-46b0-b6ac-67340a7a0245
		summarizeBy: count
		sourceColumn: INVENTDIMENSION9TZID

		annotation SummarizationSetBy = Automatic

	column INVENTDIMENSION10
		dataType: double
		lineageTag: cdad0436-ed7d-44c5-8ad6-1d3e8a7a49e3
		summarizeBy: sum
		sourceColumn: INVENTDIMENSION10

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column INVENTVERSIONID
		dataType: string
		lineageTag: ba8de79c-0e0b-4bf9-9468-aaf17c61b1f4
		summarizeBy: none
		sourceColumn: INVENTVERSIONID

		annotation SummarizationSetBy = Automatic

	column INVENTDIMENSION11
		dataType: string
		lineageTag: e8f8632b-01df-4a43-97e8-ccc669db2af2
		summarizeBy: none
		sourceColumn: INVENTDIMENSION11

		annotation SummarizationSetBy = Automatic

	column INVENTDIMENSION12
		dataType: string
		lineageTag: ffa913d5-d6d2-451c-b7e7-ed7ef6a4bbb6
		summarizeBy: none
		sourceColumn: INVENTDIMENSION12

		annotation SummarizationSetBy = Automatic

	column SHA3HASHHEX
		dataType: string
		lineageTag: 7d247834-5053-4a0b-a5b3-699f91077b46
		summarizeBy: none
		sourceColumn: SHA3HASHHEX

		annotation SummarizationSetBy = Automatic

	partition Vw_Inventory_Aging_report-c706ca5f-e2ae-4911-a931-81e6efb697cd = m
		mode: import
		source =
				let
				    Source = Sql.Database("DynatechUAT-1", "AxDB_A"),
				    dbo_Vw_Inventory_Aging_report = Source{[Schema="dbo",Item="Vw_Inventory_Aging_report_V1"]}[Data]
				in
				    dbo_Vw_Inventory_Aging_report

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

